export const localTypes = {
  ON_CHANGE: 'ON_CHANGE',
  ON_CHANGE_CAREERS: 'ON_CHANGE_CAREERS',
  ON_CHANGE_CHECK: 'ON_CHANGE_CHECK',
}

export const apiTypes = {
  GET_BOOTCAMPS_START: 'GET_BOOTCAMPS_START',
  GET_BOOTCAMPS_SUCCESS: 'GET_BOOTCAMPS_SUCCESS',
  GET_BOOTCAMPS_FAILURE: 'GET_BOOTCAMPS_FAILURE',
  GET_SINGLE_BOOTCAMP_START: 'GET_SINGLE_BOOTCAMP_START',
  GET_SINGLE_BOOTCAMP_SUCCESS: 'GET_SINGLE_BOOTCAMP_SUCCESS',
  GET_SINGLE_BOOTCAMP_FAILURE: 'GET_SINGLE_BOOTCAMP_FAILURE',
  ADD_BOOTCAMP_START: 'ADD_BOOTCAMP_START',
  ADD_BOOTCAMP_SUCCESS: 'ADD_BOOTCAMP_SUCCESS',
  ADD_BOOTCAMP_FAILURE: 'ADD_BOOTCAMP_FAILURE',
};

