const types = {
  GET_BOOTCAMPS_START: 'GET_BOOTCAMPS_START',
  GET_BOOTCAMPS_SUCCESS: 'GET_BOOTCAMPS_SUCCESS',
  GET_BOOTCAMPS_FAILURE: 'GET_BOOTCAMPS_FAILURE',
  GET_SINGLE_BOOTCAMP_START: 'GET_SINGLE_BOOTCAMP_START',
  GET_SINGLE_BOOTCAMP_SUCCESS: 'GET_SINGLE_BOOTCAMP_SUCCESS',
  GET_SINGLE_BOOTCAMP_FAILURE: 'GET_SINGLE_BOOTCAMP_FAILURE'
};

export default types;
