export const apiTypes = {
  LOGIN_USER_START: "LOGIN_USER_START",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
  LOGOUT_USER_START: "LOGOUT_USER_START",
  LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
  LOGOUT_USER_FAILURE: "LOGOUT_USER_FAILURE",
  REGISTER_USER_START: "REGISTER_USER_START",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",
  RENOVATE_TOKEN_START: "RENOVATE_TOKEN_START",
  RENOVATE_TOKEN_SUCCESS: "RENOVATE_TOKEN_SUCCESS",
  RENOVATE_TOKEN_FAILURE: "RENOVATE_TOKEN_FAILURE"
};

export const localTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER"
};
