export const apiTypes = {
  GET_REVIEWS_BY_BOOTCAMP_START: 'GET_REVIEWS_BY_BOOTCAMP_START',
  GET_REVIEWS_BY_BOOTCAMP_SUCCESS: 'GET_REVIEWS_BY_BOOTCAMP_SUCCESS',
  GET_REVIEWS_BY_BOOTCAMP_FAILURE: 'GET_REVIEWS_BY_BOOTCAMP_FAILURE',

  ADD_REVIEW_START: 'ADD_REVIEW_START',
  ADD_REVIEW_SUCCESS: 'ADD_REVIEW_SUCCESS',
  ADD_REVIEW_FAILURE: 'ADD_REVIEW_FAILURE',
};
