const types = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  LOGIN_USER_START: "LOGIN_USER_START",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
  REGISTER_USER_START: "REGISTER_USER_START",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",
  RENOVATE_TOKEN_START: "RENOVATE_TOKEN_START",
  RENOVATE_TOKEN_SUCCESS: "RENOVATE_TOKEN_SUCCESS",
  RENOVATE_TOKEN_FAILURE: "CHECK_USER_SESSION_FAILURE",
  LOGOUT_USER: "LOGOUT_USER"
};

export default types;
