const types = {
  LOGIN_USER_START: 'LOGIN_USER_START',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
  REGISTER_USER_START: 'REGISTER_USER_START',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',
  CHECK_USER_SESSION_START: 'CHECK_USER_SESSION_START',
  CHECK_USER_SESSION_SUCCESS: 'CHECK_USER_SESSION_SUCCESS',
  CHECK_USER_SESSION_FAILURE: 'CHECK_USER_SESSION_FAILURE',
  LOGOUT_USER: 'LOGOUT_USER'
};

export default types;
