export const apiTypes = {
  LOGIN_USER_START: "LOGIN_USER_START",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
  REGISTER_USER_START: "REGISTER_USER_START",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",
  RENOVATE_TOKEN_START: "RENOVATE_TOKEN_START",
  RENOVATE_TOKEN_SUCCESS: "RENOVATE_TOKEN_SUCCESS",
  RENOVATE_TOKEN_FAILURE: "RENOVATE_TOKEN_FAILURE",
  UPDATE_USER_START: "UPDATE_USER_START",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",
  FORGOT_PASSWORD_START: "FORGOT_PASSWORD_START",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",
};

export const localTypes = {
  CLEAN_USER_STATE: 'CLEAN_USER_STATE',
  LOGOUT_USER: "LOGOUT_USER",
  SET_CURRENT_USER: 'SET_CURRENT_USER'
};
